package com.oracle.five.cloud_disk.beans;

import java.util.List;

public class CloudFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.FILE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.FATHER_FILE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private CloudFile fatherFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.FILE_NAME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.REAL_PATH
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private String realPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.IS_DELETE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Boolean isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.SCAN_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer scanCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.SAVE_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer saveCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.DOWNLOAD_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer downloadCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FILE.TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    private Integer type;
    
    private List<CloudFile> childFiles;
    

    public List<CloudFile> getChildFiles() {
		return childFiles;
	}

	public void setChildFiles(List<CloudFile> childFiles) {
		this.childFiles = childFiles;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE.FILE_ID
     *
     * @return the value of FILE.FILE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE.FILE_ID
     *
     * @param fileId the value for FILE.FILE_ID
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    

    public CloudFile getFatherFile() {
		return fatherFile;
	}

	public void setFatherFile(CloudFile fatherFile) {
		this.fatherFile = fatherFile;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE.FILE_NAME
     *
     * @return the value of FILE.FILE_NAME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE.FILE_NAME
     *
     * @param fileName the value for FILE.FILE_NAME
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE.REAL_PATH
     *
     * @return the value of FILE.REAL_PATH
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public String getRealPath() {
        return realPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE.REAL_PATH
     *
     * @param realPath the value for FILE.REAL_PATH
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setRealPath(String realPath) {
        this.realPath = realPath == null ? null : realPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE.IS_DELETE
     *
     * @return the value of FILE.IS_DELETE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE.IS_DELETE
     *
     * @param isDelete the value for FILE.IS_DELETE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE.SCAN_COUNT
     *
     * @return the value of FILE.SCAN_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getScanCount() {
        return scanCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE.SCAN_COUNT
     *
     * @param scanCount the value for FILE.SCAN_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setScanCount(Integer scanCount) {
        this.scanCount = scanCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE.SAVE_COUNT
     *
     * @return the value of FILE.SAVE_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getSaveCount() {
        return saveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE.SAVE_COUNT
     *
     * @param saveCount the value for FILE.SAVE_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setSaveCount(Integer saveCount) {
        this.saveCount = saveCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE.DOWNLOAD_COUNT
     *
     * @return the value of FILE.DOWNLOAD_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getDownloadCount() {
        return downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE.DOWNLOAD_COUNT
     *
     * @param downloadCount the value for FILE.DOWNLOAD_COUNT
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setDownloadCount(Integer downloadCount) {
        this.downloadCount = downloadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FILE.TYPE
     *
     * @return the value of FILE.TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FILE.TYPE
     *
     * @param type the value for FILE.TYPE
     *
     * @mbg.generated Sat Aug 05 14:04:49 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}